### ISSUE TITLE
Bug: rollout with kubectl breaks

### ISSUE THREAD

**Issue by Avokadoen** [nlnwa/gowarcserver#15] opened 2021-03-12 10:34 UTC
**Describe the bug**
It seems like badger refuses connection to the new pod with rollout strategy. The scope of fixing this bug might be to big to be worth it.

@maeb can expand this report if he wants (i.e steps to reproduce)

**To Reproduce** 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by maeb** [comment] 2021-06-18 10:59
The solution to this is to configure deployment with a different strategy so it is deployment specific:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowarc-server
spec:
  strategy:
    type: Recreate
```

**Comment by maeb** [comment] 2021-06-18 11:03
So this is not a bug and can not be fixed in code. Badger presumably use a lock file or something to prevent multiple processes from using the badger database simultanously.

**Closed** 2021-06-21 09:32 UTC
Labels: bug, wontfix
